llvm_version: "15.0.7-20260801"
llvm_archive: "Clang-15.0.7-20260801.tar.gz"
llvm_url: "https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20260801-release/Clang-15.0.7-20260801.tar.gz"
cache_subdir: ".cache/noobie-kernel-toolchains"
