name: NoobieKernelRE Builder

on:
  workflow_dispatch:
    inputs:
      defconfig:
        description: Kernel defconfig
        required: true
        default: Noobie_SU_defconfig
        type: string

      resukisu:
        description: ReSukiSU / KernelSU integration
        required: true
        default: enabled
        type: choice
        options:
          - enabled
          - disabled

      gpu_driver:
        description: GPU driver version
        required: true
        default: r25p
        type: choice
        options:
          - r25p
          - r32p

      enable_nomount:
        description: Enable NoMount
        required: true
        default: false
        type: boolean

      nomount_ref:
        description: NoMount version / branch / tag
        required: true
        default: v2.0.0
        type: string

      localversion:
        description: Kernel LOCALVERSION suffix
        required: true
        default: -ver.1.03-GA
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow
        run: |
          echo "Workflow dispatch works."
          echo "Defconfig: ${{ inputs.defconfig }}"
          echo "GPU: ${{ inputs.gpu_driver }}"
          echo "ReSukiSU: ${{ inputs.resukisu }}"
